use_frameworks!

platform :ios, '8.0'

target 'HSYManagerKit_Example' do
  pod 'HSYManagerKit', :path => '../'

  target 'HSYManagerKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
