use_frameworks!

platform :ios, '8.0'

target 'HSYManagerKit_Example' do
  pod 'HSYManagerKit', :path => '../'

  target 'HSYManagerKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'HSYMacroKit', :git=> 'https://github.com/huangsongyao/HSYMacroKit.git'
    pod 'HSYMethodsToolsKit', :git=> 'https://github.com/huangsongyao/HSYMethodsToolsKit.git'
    pod 'HSYDatabaseToolsKit', :git=> 'https://github.com/huangsongyao/HSYDatabaseToolsKit.git'
    
  end
end
